[package]
name = "tex-mex"
version = "0.1.0"
authors = ["Kenny Goodin <kennethbgoodin@gmail.com>"]

[dependencies]
serde = "1.0.92"
serde_json = "1.0.39"
reqwest = "0.9.18"
textwrap = { version = "0.11.0", features = ["term_size"] }